[package]
name = "grainx"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
crossterm = "0.27"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
